CREATE TABLE MEMBER (
	seq BIGINT AUTO_INCREMENT,
	eamil VARCHAR(65) NOT NULL UNIQUE,
	password VARCHAR(65) NOT NULL,
	name VARCHAR(45) NOT NULL,
	mobile VARCHAR(15) NOT NULL,
	authority ENUM('MEMBER', 'ADMIN') DEFAULT 'MEMBER',
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	modifiedAt DATETIME,
	PRIMARY KEY(seq)
);
